Headers and URLs
spaceuptech/mission-control pull request #233
Opened 2021-02-02 17:02 UTC by shubham4443

1. Added support for traffic splitting based on headers and urls.
2. Style of collapse component inside a form was globally modified specifically for advanced settings. Added a class name for such components so they don't override other collapses.

2021-02-23 15:43 UTC, Saif-Ali-Kamal commented
- matchers payload is not received in request and not stored in redux
- in matchers headers if type is check presence there should be only one field i.e. key

2021-02-27 12:22 UTC, Saif-Ali-Kamal commented
- matchers are not visible at time of edit, maybe there is issue in initialValue
- also test it by putting matcher in mirage data

2021-03-01 14:25 UTC, Saif-Ali-Kamal approved these changes

2021-03-02 12:55 UTC, Saif-Ali-Kamal requested changes
- matchers is optional but if in url and headers if one of the value is filled make other value in respective section mandatory
- try to solve warning that are present in console

2021-03-02 12:55 UTC, Saif-Ali-Kamal commented on src/components/deployments/routing-modal/RoutingModal.jsx
> +                                              <Select.Option value="checkPresence">Check presence</Select.Option>
change checkPresence to check-presence

2021-03-05 05:56 UTC, sharadregoti approved these changes

2021-03-05 05:56 UTC, merged